In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\Avinash\Desktop\newfile.csv")

In [3]:
data.head()

,a,b,c,d,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 321,Unnamed: 322,Unnamed: 323,Unnamed: 324,Unnamed: 325,Unnamed: 326,Unnamed: 327,Unnamed: 328,Unnamed: 329,Unnamed: 330
0,-55.0,0.000015,0.000015,0.000014,0.000014,0.000013,0.000013,0.000013,0.000012,0.000012,...,0.000009,0.000009,0.000009,0.000009,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008
1,-51.4,0.000015,0.000015,0.000014,0.000014,0.000013,0.000013,0.000013,0.000012,0.000012,...,0.000009,0.000009,0.000009,0.000009,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008
2,-47.8,0.000015,0.000015,0.000014,0.000014,0.000013,0.000013,0.000013,0.000012,0.000012,...,0.000009,0.000009,0.000009,0.000009,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008
3,-44.2,0.000015,0.000015,0.000014,0.000014,0.000013,0.000013,0.000013,0.000012,0.000012,...,0.000009,0.000009,0.000009,0.000009,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008
4,-40.6,0.000015,0.000015,0.000014,0.000014,0.000013,0.000013,0.000013,0.000012,0.000012,...,0.000009,0.000009,0.000009,0.000009,0.000008,0.000008,0.000008,0.000008,0.000008,0.000008

In [4]:
X = data.iloc[: , 1:]

In [5]:
print(X)

           b         c         d  Unnamed: 4  Unnamed: 5  Unnamed: 6  \
0   0.000015  0.000015  0.000014    0.000014    0.000013    0.000013
1   0.000015  0.000015  0.000014    0.000014    0.000013    0.000013
2   0.000015  0.000015  0.000014    0.000014    0.000013    0.000013
3   0.000015  0.000015  0.000014    0.000014    0.000013    0.000013
4   0.000015  0.000015  0.000014    0.000014    0.000013    0.000013
5   0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
6   0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
7   0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
8   0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
9   0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
10  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
11  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
12  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
13  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
14  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
15  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
16  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
17  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
18  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
19  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
20  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
21  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
22  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
23  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
24  0.000015  0.000015  0.000014    0.000014    0.000014    0.000013
25  0.000016  0.000015  0.000014    0.000014    0.000014    0.000013
26  0.000016  0.000015  0.000014    0.000014    0.000014    0.000013
27  0.000016  0.000015  0.000014    0.000014    0.000014    0.000013
28  0.000016  0.000015  0.000014    0.000014    0.000014    0.000013
29  0.000016  0.000015  0.000014    0.000014    0.000014    0.000013
30  0.000016  0.000015  0.000014    0.000014    0.000014    0.000013
31  0.000016  0.000015  0.000014    0.000014    0.000014    0.000013
32  0.000016  0.000015  0.000014    0.000014    0.000014    0.000013
33  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
34  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
35  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
36  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
37  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
38  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
39  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
40  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
41  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
42  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
43  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
44  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
45  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
46  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
47  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
48  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
49  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013
50  0.000016  0.000015  0.000015    0.000014    0.000014    0.000013

    Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  ...  Unnamed: 321  \
0     0.000013    0.000012    0.000012     0.000012  ...      0.000009
1     0.000013    0.000012    0.000012     0.000012  ...      0.000009
2     0.000013    0.000012    0.000012     0.000012  ...      0.000009
3     0.000013    0.000012    0.000012     0.000012  ...      0.000009
4     0.000013    0.000012    0.000012     0.000012  ...      0.000009
5     0.000013    0.000012    0.000012     0.000012  ...      0.000009
6     0.000013    0.000012    0.000012     0.000012  ...      0.000009
7     0.000013    0.000012    0.000012     0.000012  ...      0.000009
8     0.000013    0.000012    0.000012     0.000012  ...      0.000009
9     0.000013    0.000012    0.000012     0.000012  ...      0.000009
10    0.000013    0.000012    0.000012     0.000012  ...      0.000009
11    0.000013    0.000012    0.000012     0.000012  ...      0.000009
12    0.000013    0.000012    0.000012     0.000012  ...      0.000009
13    0.000013    0.000012    0.000012     0.000012  ...      0.000009
14    0.000013    0.000012    0.000012     0.000012  ...      0.000009
15    0.000013    0.000012    0.000012     0.000012  ...      0.000009
16    0.000013    0.000012    0.000012     0.000012  ...      0.000009
17    0.000013    0.000012    0.000012     0.000012  ...      0.000009
18    0.000013    0.000012    0.000012     0.000012  ...      0.000009
19    0.000013    0.000012    0.000012     0.000012  ...      0.000009
20    0.000013    0.000012    0.000012     0.000012  ...      0.000009
21    0.000013    0.000012    0.000012     0.000012  ...      0.000009
22    0.000013    0.000012    0.000012     0.000012  ...      0.000009
23    0.000013    0.000013    0.000012     0.000012  ...      0.000009
24    0.000013    0.000013    0.000012     0.000012  ...      0.000009
25    0.000013    0.000013    0.000012     0.000012  ...      0.000009
26    0.000013    0.000013    0.000012     0.000012  ...      0.000009
27    0.000013    0.000013    0.000012     0.000012  ...      0.000009
28    0.000013    0.000013    0.000012     0.000012  ...      0.000009
29    0.000013    0.000013    0.000012     0.000012  ...      0.000009
30    0.000013    0.000013    0.000012     0.000012  ...      0.000009
31    0.000013    0.000013    0.000012     0.000012  ...      0.000009
32    0.000013    0.000013    0.000012     0.000012  ...      0.000009
33    0.000013    0.000013    0.000012     0.000012  ...      0.000009
34    0.000013    0.000013    0.000012     0.000012  ...      0.000009
35    0.000013    0.000013    0.000012     0.000012  ...      0.000009
36    0.000013    0.000013    0.000012     0.000012  ...      0.000009
37    0.000013    0.000013    0.000012     0.000012  ...      0.000009
38    0.000013    0.000013    0.000012     0.000012  ...      0.000009
39    0.000013    0.000013    0.000012     0.000012  ...      0.000009
40    0.000013    0.000013    0.000012     0.000012  ...      0.000009
41    0.000013    0.000013    0.000012     0.000012  ...      0.000009
42    0.000013    0.000013    0.000012     0.000012  ...      0.000009
43    0.000013    0.000013    0.000012     0.000012  ...      0.000009
44    0.000013    0.000013    0.000012     0.000012  ...      0.000009
45    0.000013    0.000013    0.000012     0.000012  ...      0.000009
46    0.000013    0.000013    0.000012     0.000012  ...      0.000009
47    0.000013    0.000013    0.000012     0.000012  ...      0.000009
48    0.000013    0.000013    0.000012     0.000012  ...      0.000009
49    0.000013    0.000013    0.000012     0.000012  ...      0.000009
50    0.000013    0.000013    0.000012     0.000012  ...      0.000009

    Unnamed: 322  Unnamed: 323  Unnamed: 324  Unnamed: 325  Unnamed: 326  \
0       0.000009      0.000009      0.000009      0.000008      0.000008
1       0.000009      0.000009      0.000009      0.000008      0.000008
2       0.000009      0.000009      0.000009      0.000008      0.000008
3       0.000009      0.000009      0.000009      0.000008      0.000008
4       0.000009      0.000009      0.000009      0.000008      0.000008
5       0.000009      0.000009      0.000009      0.000008      0.000008
6       0.000009      0.000009      0.000009      0.000008      0.000008
7       0.000009      0.000009      0.000009      0.000008      0.000008
8       0.000009      0.000009      0.000009      0.000008      0.000008
9       0.000009      0.000009      0.000009      0.000008      0.000008
10      0.000009      0.000009      0.000009      0.000008      0.000008
11      0.000009      0.000009      0.000009      0.000008      0.000008
12      0.000009      0.000009      0.000009      0.000008      0.000008
13      0.000009      0.000009      0.000009      0.000008      0.000008
14      0.000009      0.000009      0.000009      0.000008      0.000008
15      0.000009      0.000009      0.000009      0.000008      0.000008
16      0.000009      0.000009      0.000009      0.000008      0.000008
17      0.000009      0.000009      0.000009      0.000008      0.000008
18      0.000009      0.000009      0.000009      0.000008      0.000008
19      0.000009      0.000009      0.000009      0.000008      0.000008
20      0.000009      0.000009      0.000009      0.000008      0.000008
21      0.000009      0.000009      0.000009      0.000008      0.000008
22      0.000009      0.000009      0.000009      0.000008      0.000008
23      0.000009      0.000009      0.000009      0.000008      0.000008
24      0.000009      0.000009      0.000009      0.000008      0.000008
25      0.000009      0.000009      0.000009      0.000008      0.000008
26      0.000009      0.000009      0.000009      0.000008      0.000008
27      0.000009      0.000009      0.000009      0.000008      0.000008
28      0.000009      0.000009      0.000009      0.000008      0.000008
29      0.000009      0.000009      0.000009      0.000008      0.000008
30      0.000009      0.000009      0.000009      0.000008      0.000008
31      0.000009      0.000009      0.000009      0.000008      0.000008
32      0.000009      0.000009      0.000009      0.000008      0.000008
33      0.000009      0.000009      0.000009      0.000008      0.000008
34      0.000009      0.000009      0.000009      0.000008      0.000008
35      0.000009      0.000009      0.000009      0.000008      0.000008
36      0.000009      0.000009      0.000009      0.000008      0.000008
37      0.000009      0.000009      0.000009      0.000008      0.000008
38      0.000009      0.000009      0.000009      0.000008      0.000008
39      0.000009      0.000009      0.000009      0.000008      0.000008
40      0.000009      0.000009      0.000009      0.000008      0.000008
41      0.000009      0.000009      0.000009      0.000008      0.000008
42      0.000009      0.000009      0.000008      0.000008      0.000008
43      0.000009      0.000009      0.000008      0.000008      0.000008
44      0.000009      0.000009      0.000008      0.000008      0.000008
45      0.000009      0.000009      0.000008      0.000008      0.000008
46      0.000009      0.000009      0.000008      0.000008      0.000008
47      0.000009      0.000009      0.000008      0.000008      0.000008
48      0.000009      0.000009      0.000008      0.000008      0.000008
49      0.000009      0.000009      0.000008      0.000008      0.000008
50      0.000009      0.000009      0.000008      0.000008      0.000008

    Unnamed: 327  Unnamed: 328  Unnamed: 329  Unnamed: 330
0       0.000008      0.000008      0.000008      0.000008
1       0.000008      0.000008      0.000008      0.000008
2       0.000008      0.000008      0.000008      0.000008
3       0.000008      0.000008      0.000008      0.000008
4       0.000008      0.000008      0.000008      0.000008
5       0.000008      0.000008      0.000008      0.000008
6       0.000008      0.000008      0.000008      0.000008
7       0.000008      0.000008      0.000008      0.000008
8       0.000008      0.000008      0.000008      0.000008
9       0.000008      0.000008      0.000008      0.000008
10      0.000008      0.000008      0.000008      0.000008
11      0.000008      0.000008      0.000008      0.000008
12      0.000008      0.000008      0.000008      0.000008
13      0.000008      0.000008      0.000008      0.000008
14      0.000008      0.000008      0.000008      0.000008
15      0.000008      0.000008      0.000008      0.000008
16      0.000008      0.000008      0.000008      0.000008
17      0.000008      0.000008      0.000008      0.000008
18      0.000008      0.000008      0.000008      0.000008
19      0.000008      0.000008      0.000008      0.000008
20      0.000008      0.000008      0.000008      0.000008
21      0.000008      0.000008      0.000008      0.000008
22      0.000008      0.000008      0.000008      0.000008
23      0.000008      0.000008      0.000008      0.000008
24      0.000008      0.000008      0.000008      0.000008
25      0.000008      0.000008      0.000008      0.000008
26      0.000008      0.000008      0.000008      0.000008
27      0.000008      0.000008      0.000008      0.000008
28      0.000008      0.000008      0.000008      0.000008
29      0.000008      0.000008      0.000008      0.000008
30      0.000008      0.000008      0.000008      0.000008
31      0.000008      0.000008      0.000008      0.000008
32      0.000008      0.000008      0.000008      0.000008
33      0.000008      0.000008      0.000008      0.000008
34      0.000008      0.000008      0.000008      0.000008
35      0.000008      0.000008      0.000008      0.000008
36      0.000008      0.000008      0.000008      0.000008
37      0.000008      0.000008      0.000008      0.000008
38      0.000008      0.000008      0.000008      0.000008
39      0.000008      0.000008      0.000008      0.000008
40      0.000008      0.000008      0.000008      0.000008
41      0.000008      0.000008      0.000008      0.000008
42      0.000008      0.000008      0.000008      0.000008
43      0.000008      0.000008      0.000008      0.000008
44      0.000008      0.000008      0.000008      0.000008
45      0.000008      0.000008      0.000008      0.000008
46      0.000008      0.000008      0.000008      0.000008
47      0.000008      0.000008      0.000008      0.000008
48      0.000008      0.000008      0.000008      0.000008
49      0.000008      0.000008      0.000008      0.000008
50      0.000008      0.000008      0.000008      0.000008

[51 rows x 330 columns]

In [6]:
y = pd.Series(X.values.ravel('F'))

In [7]:
y.to_csv('cref1.csv')

In [8]:
print(y)

0        0.000015
1        0.000015
2        0.000015
3        0.000015
4        0.000015
           ...
16825    0.000008
16826    0.000008
16827    0.000008
16828    0.000008
16829    0.000008
Length: 16830, dtype: float64

In [9]:
t = data.iloc[:,0:1]

In [10]:
print(t)
print(data.columns)

        a
0   -55.0
1   -51.4
2   -47.8
3   -44.2
4   -40.6
5   -37.0
6   -33.4
7   -29.8
8   -26.2
9   -22.6
10  -19.0
11  -15.4
12  -11.8
13   -8.2
14   -4.6
15   -1.0
16    2.6
17    6.2
18    9.8
19   13.4
20   17.0
21   20.6
22   24.2
23   27.8
24   31.4
25   35.0
26   38.6
27   42.2
28   45.8
29   49.4
30   53.0
31   56.6
32   60.2
33   63.8
34   67.4
35   71.0
36   74.6
37   78.2
38   81.8
39   85.4
40   89.0
41   92.6
42   96.2
43   99.8
44  103.4
45  107.0
46  110.6
47  114.2
48  117.8
49  121.4
50  125.0
Index(['a', 'b', 'c', 'd', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 321', 'Unnamed: 322', 'Unnamed: 323', 'Unnamed: 324',
       'Unnamed: 325', 'Unnamed: 326', 'Unnamed: 327', 'Unnamed: 328',
       'Unnamed: 329', 'Unnamed: 330'],
      dtype='object', length=331)

In [18]:
dataset = pd.read_csv("test_final.csv")

FileNotFoundError: [Errno 2] File test_final.csv does not exist: 'test_final.csv'

In [12]:
len(dataset.iloc[: , 0:1])

16830

In [13]:
dataset.head()

   Unnamed: 0         0
0           0  0.000015
1           1  0.000015
2           2  0.000015
3           3  0.000015
4           4  0.000015

In [14]:
len(dataset)

16830

In [90]:
x1 = 1
for i in range(0,len(dataset),1581):
    dataset.iloc[i:i+1581,4:] = x1
    x1+=0.2
print(dataset)
dataset.to_csv("test_final.csv")

       Unnamed: 0         0      1    2    4    K
0               0  0.000015  -55.0  1.1  1.0  1.0
1               1  0.000015  -51.4  1.1  1.0  1.0
2               2  0.000015  -47.8  1.1  1.0  1.0
3               3  0.000015  -44.2  1.1  1.0  1.0
4               4  0.000015  -40.6  1.1  1.0  1.0
...           ...       ...    ...  ...  ...  ...
16825       16825  0.000008  110.6  1.1  3.0  3.0
16826       16826  0.000008  114.2  1.1  3.0  3.0
16827       16827  0.000008  117.8  1.1  3.0  3.0
16828       16828  0.000008  121.4  1.1  3.0  3.0
16829       16829  0.000008  125.0  1.1  3.0  3.0

[16830 rows x 6 columns]

In [89]:
dataset["K"].head(51)

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
35    1.0
36    1.0
37    1.0
38    1.0
39    1.0
40    1.0
41    1.0
42    1.0
43    1.0
44    1.0
45    1.0
46    1.0
47    1.0
48    1.0
49    1.0
50    1.0
Name: K, dtype: float64

In [16]:
x1 = 33000
while(x1<=63000):
    for i in range(0,len(dataset),51):
        dataset.iloc[i:i+51,5:] = x1
        x1+=1000
    print(dataset)
#dataset.to_csv("test_final.csv")

       Unnamed: 0         0
0               0  0.000015
1               1  0.000015
2               2  0.000015
3               3  0.000015
4               4  0.000015
...           ...       ...
16825       16825  0.000008
16826       16826  0.000008
16827       16827  0.000008
16828       16828  0.000008
16829       16829  0.000008

[16830 rows x 2 columns]

In [6]:
dataset1 = pd.read_csv(r"C:\Users\Avinash\test_final.csv")
!pip install goto-statement

Collecting goto-statement
  Downloading goto_statement-1.2-py2.py3-none-any.whl (5.6 kB)
Installing collected packages: goto-statement
Successfully installed goto-statement-1.2

In [38]:
x1 = 33000
for i in range(0,len(dataset1),51):
    dataset1.iloc[i:i+51,5:] = x1
    x1+=1000
    if x1==64000:
        x1=33000
        continue
print(dataset1)
dataset1.to_csv("test_final_final_final.csv")

       Unnamed: 0      X         Y      Z    K        T
0               0      0  0.000015  -55.0  1.0  33000.0
1               1      1  0.000015  -51.4  1.0  33000.0
2               2      2  0.000015  -47.8  1.0  33000.0
3               3      3  0.000015  -44.2  1.0  33000.0
4               4      4  0.000015  -40.6  1.0  33000.0
...           ...    ...       ...    ...  ...      ...
16825       16825  16825  0.000008  110.6  3.0  52000.0
16826       16826  16826  0.000008  114.2  3.0  52000.0
16827       16827  16827  0.000008  117.8  3.0  52000.0
16828       16828  16828  0.000008  121.4  3.0  52000.0
16829       16829  16829  0.000008  125.0  3.0  52000.0

[16830 rows x 6 columns]

In [34]:
dataset1.tail(60)

       Unnamed: 0      X         Y      Z    K        T
16770       16770  16770  0.000008   96.2  3.0  61000.0
16771       16771  16771  0.000008   99.8  3.0  61000.0
16772       16772  16772  0.000008  103.4  3.0  61000.0
16773       16773  16773  0.000008  107.0  3.0  61000.0
16774       16774  16774  0.000008  110.6  3.0  61000.0
16775       16775  16775  0.000008  114.2  3.0  61000.0
16776       16776  16776  0.000008  117.8  3.0  61000.0
16777       16777  16777  0.000008  121.4  3.0  61000.0
16778       16778  16778  0.000008  125.0  3.0  61000.0
16779       16779  16779  0.000008  -55.0  3.0  62000.0
16780       16780  16780  0.000008  -51.4  3.0  62000.0
16781       16781  16781  0.000008  -47.8  3.0  62000.0
16782       16782  16782  0.000008  -44.2  3.0  62000.0
16783       16783  16783  0.000008  -40.6  3.0  62000.0
16784       16784  16784  0.000008  -37.0  3.0  62000.0
16785       16785  16785  0.000008  -33.4  3.0  62000.0
16786       16786  16786  0.000008  -29.8  3.0  62000.0
16787       16787  16787  0.000008  -26.2  3.0  62000.0
16788       16788  16788  0.000008  -22.6  3.0  62000.0
16789       16789  16789  0.000008  -19.0  3.0  62000.0
16790       16790  16790  0.000008  -15.4  3.0  62000.0
16791       16791  16791  0.000008  -11.8  3.0  62000.0
16792       16792  16792  0.000008   -8.2  3.0  62000.0
16793       16793  16793  0.000008   -4.6  3.0  62000.0
16794       16794  16794  0.000008   -1.0  3.0  62000.0
16795       16795  16795  0.000008    2.6  3.0  62000.0
16796       16796  16796  0.000008    6.2  3.0  62000.0
16797       16797  16797  0.000008    9.8  3.0  62000.0
16798       16798  16798  0.000008   13.4  3.0  62000.0
16799       16799  16799  0.000008   17.0  3.0  62000.0
16800       16800  16800  0.000008   20.6  3.0  62000.0
16801       16801  16801  0.000008   24.2  3.0  62000.0
16802       16802  16802  0.000008   27.8  3.0  62000.0
16803       16803  16803  0.000008   31.4  3.0  62000.0
16804       16804  16804  0.000008   35.0  3.0  62000.0
16805       16805  16805  0.000008   38.6  3.0  62000.0
16806       16806  16806  0.000008   42.2  3.0  62000.0
16807       16807  16807  0.000008   45.8  3.0  62000.0
16808       16808  16808  0.000008   49.4  3.0  62000.0
16809       16809  16809  0.000008   53.0  3.0  62000.0
16810       16810  16810  0.000008   56.6  3.0  62000.0
16811       16811  16811  0.000008   60.2  3.0  62000.0
16812       16812  16812  0.000008   63.8  3.0  62000.0
16813       16813  16813  0.000008   67.4  3.0  62000.0
16814       16814  16814  0.000008   71.0  3.0  62000.0
16815       16815  16815  0.000008   74.6  3.0  62000.0
16816       16816  16816  0.000008   78.2  3.0  62000.0
16817       16817  16817  0.000008   81.8  3.0  62000.0
16818       16818  16818  0.000008   85.4  3.0  62000.0
16819       16819  16819  0.000008   89.0  3.0  62000.0
16820       16820  16820  0.000008   92.6  3.0  62000.0
16821       16821  16821  0.000008   96.2  3.0  62000.0
16822       16822  16822  0.000008   99.8  3.0  62000.0
16823       16823  16823  0.000008  103.4  3.0  62000.0
16824       16824  16824  0.000008  107.0  3.0  62000.0
16825       16825  16825  0.000008  110.6  3.0  62000.0
16826       16826  16826  0.000008  114.2  3.0  62000.0
16827       16827  16827  0.000008  117.8  3.0  62000.0
16828       16828  16828  0.000008  121.4  3.0  62000.0
16829       16829  16829  0.000008  125.0  3.0  62000.0

In [41]:
for k in range(12):
    x1 = 33000
    for i in range(32):
        for j in range(52):
            dataset1.iloc[j,5:] = x1
        x1+=1000
print(dataset1)

       Unnamed: 0      X         Y      Z    K        T
0               0      0  0.000015  -55.0  1.0  64000.0
1               1      1  0.000015  -51.4  1.0  64000.0
2               2      2  0.000015  -47.8  1.0  64000.0
3               3      3  0.000015  -44.2  1.0  64000.0
4               4      4  0.000015  -40.6  1.0  64000.0
...           ...    ...       ...    ...  ...      ...
16825       16825  16825  0.000008  110.6  3.0  52000.0
16826       16826  16826  0.000008  114.2  3.0  52000.0
16827       16827  16827  0.000008  117.8  3.0  52000.0
16828       16828  16828  0.000008  121.4  3.0  52000.0
16829       16829  16829  0.000008  125.0  3.0  52000.0

[16830 rows x 6 columns]